<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Account_name</name>
   <tag></tag>
   <elementGuidId>cbc6f120-1234-4974-8b96-0f811e6553f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@name='Name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;Name&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = concat(&quot;//*[@name=&quot; , &quot;'&quot; , &quot;Name&quot; , &quot;'&quot; , &quot;]&quot;) and @placeholder = 'First Name' and @type = 'text' and @class = 'firstName compoundBorderBottom form-element__row input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eac40e24-1e24-410d-85a8-25aef3756d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>34023d21-36b6-4418-a908-482a6ea96854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>//*[@name='Name']</value>
      <webElementGuid>069d01d4-ab58-4370-8195-3c8a168b3616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First Name</value>
      <webElementGuid>7b5175e9-5b95-4d5f-9c1a-0be359f1e84e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e1a1d684-02d7-4fae-8e8c-8c184694cdd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>firstName compoundBorderBottom form-element__row input</value>
      <webElementGuid>c524a726-0b0d-4991-9daf-4e89cf0fe5c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>153:1731;a</value>
      <webElementGuid>bb1c377d-d9cd-4353-aa4e-53eb52165709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-interactive-lib-uid</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>0680caa6-f2c6-446b-8f0d-de7c23c40355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6450a840-6fa3-4905-b8b0-fd1ca56a119d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;149:1731;a&quot;)</value>
      <webElementGuid>9bb6dad2-692a-4a12-9d2b-5910e71a6ebb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='149:1731;a']</value>
      <webElementGuid>4371ca46-594a-4a5b-a77a-d47d9bef1dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div[2]/input</value>
      <webElementGuid>546f0ce5-a76a-4842-b207-aa68cf347eca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
