<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Inputfields</name>
   <tag></tag>
   <elementGuidId>b20bf623-65bd-414c-b1ce-b79a6e85eed0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@name='Name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;Name&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name='${inputfields}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2758119-bd60-46b6-98a9-dbf088f64a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>d87b327a-1279-4122-9399-4e5e67234514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name='${inputfields}']</value>
      <webElementGuid>a283f804-9443-4dea-849e-6ea651e0b58e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='149:1731;a']</value>
      <webElementGuid>bc6c96bb-5cb7-43ed-be35-15f182ddfe35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div[2]/input</value>
      <webElementGuid>573c97b6-3204-4204-b9ab-b9755aba69d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
